version: '2'
services:
  redmine:
    build:
        context: ./
        dockerfile: Dockerfile
    ports:
      - '80:3000'
    environment:
      - REDMINE_DB_PORT_NUMBER=3306
      - REDMINE_DB_MYSQL=redminecustomfields.chydejwyje5r.us-west-2.rds.amazonaws.com
      - REDMINE_DB_USERNAME=redmine
      - REDMINE_DB_PASSWORD=bT\v>R~KSGQD=t4